PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE roster (   id       TEXT PRIMARY KEY,   initials TEXT NOT NULL,   name     TEXT NOT NULL,   role     TEXT NOT NULL,   meta     TEXT NOT NULL,   sort_order INTEGER );
INSERT INTO "roster" ("id","initials","name","role","meta","sort_order") VALUES('p1','SY','HMWR Syro','Cute ni sy','Joined 2021 · Mp - casual',1);
INSERT INTO "roster" ("id","initials","name","role","meta","sort_order") VALUES('p2','PAO','HMWR Paopao','N/A','Joined 2026 · Clan Master',2);
INSERT INTO "roster" ("id","initials","name","role","meta","sort_order") VALUES('p3','IYA','HMWR Iya','maingay','Joined 2025 ·',3);
INSERT INTO "roster" ("id","initials","name","role","meta","sort_order") VALUES('p4','CEF','HMWR cef','N/A','Joined 2025 · ',4);
INSERT INTO "roster" ("id","initials","name","role","meta","sort_order") VALUES('p1787831209526','K','HMWR Ryuuu1','Basta','Joined 2025 •',NULL);
INSERT INTO "roster" ("id","initials","name","role","meta","sort_order") VALUES('p1787837886891','LOT','HMWR kulot','Substitute','Rank: Grandmaster 2 · Discord: Himawari',NULL);
CREATE TABLE announcements (   id    TEXT PRIMARY KEY,   title TEXT NOT NULL,   body  TEXT NOT NULL,   date  TEXT NOT NULL );
INSERT INTO "announcements" ("id","title","body","date") VALUES('a1','Scrim block vs Nightshade opens Friday','Signups open in #scrims. Bo3, 6v6 SnD/Hardpoint/Control rotation.','2026-08-22');
INSERT INTO "announcements" ("id","title","body","date") VALUES('a1787832456434','Bisakol','Bisdak ','2026-09-01');
INSERT INTO "announcements" ("id","title","body","date") VALUES('a1787832678235','hello join na bisaya','Pindotin mo lang ang join button tas bahala ka na','2026-08-27');
INSERT INTO "announcements" ("id","title","body","date") VALUES('a1787838004717','Hello bisaya','Bisaya','2026-08-27');
INSERT INTO "announcements" ("id","title","body","date") VALUES('a1787869637509','Namaste ','Sawadika','2026-08-28');
CREATE TABLE tournaments (   id     TEXT PRIMARY KEY,   name   TEXT NOT NULL,   date   TEXT NOT NULL,   format TEXT NOT NULL,   status TEXT NOT NULL );
INSERT INTO "tournaments" ("id","name","date","format","status") VALUES('t1','Sunflower Open — August','2026-08-30','Single elimination','Upcoming');
INSERT INTO "tournaments" ("id","name","date","format","status") VALUES('t2','Community Cup #4','2026-07-19','Round robin','Completed — Himawari placed 2nd');
CREATE TABLE applicants (   id      TEXT PRIMARY KEY,   ign     TEXT NOT NULL,   rank    TEXT NOT NULL,   discord TEXT NOT NULL,   notes   TEXT,   date    TEXT NOT NULL );
CREATE TABLE roster_members (     id INTEGER PRIMARY KEY AUTOINCREMENT,     role TEXT CHECK(role IN ('Leader', 'Admin', 'Officer', 'Member')) );
CREATE TABLE brackets (     id INTEGER PRIMARY KEY AUTOINCREMENT,     title TEXT NOT NULL,     bracket_data TEXT NOT NULL,     published_to_home INTEGER DEFAULT 0,     updated_at DATETIME DEFAULT CURRENT_TIMESTAMP );
DELETE FROM sqlite_sequence;
